// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    //print(defaultTargetPlatform);
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiNlTPxdUQaGlwrnRtAK5DMiYssG8kQt0',
    appId: '1:142994986628:web:e275e246bc64fa3ffa94d1',
    messagingSenderId: '142994986628',
    projectId: 'spotifyclone-20250215',
    authDomain: 'spotifyclone-20250215.firebaseapp.com',
    storageBucket: 'spotifyclone-20250215.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8L5qv547oKNENKVtL2dJGpYWiV8DzA4',
    appId: '1:142994986628:android:e43e3c73be490397fa94d1',
    messagingSenderId: '142994986628',
    projectId: 'spotifyclone-20250215',
    storageBucket: 'spotifyclone-20250215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1zz3watn5w9EzljUiw1Th-Vz-nvndNds',
    appId: '1:142994986628:ios:15bbb8f5a431bde1fa94d1',
    messagingSenderId: '142994986628',
    projectId: 'spotifyclone-20250215',
    storageBucket: 'spotifyclone-20250215.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1zz3watn5w9EzljUiw1Th-Vz-nvndNds',
    appId: '1:142994986628:ios:15bbb8f5a431bde1fa94d1',
    messagingSenderId: '142994986628',
    projectId: 'spotifyclone-20250215',
    storageBucket: 'spotifyclone-20250215.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyDwxQPdGbSiD5dcVGh88R23lGMImKCxtKs',
  //   appId: '1:426509858399:web:7367e344006c4003264dea',
  //   messagingSenderId: '426509858399',
  //   projectId: 'spotify0101',
  //   authDomain: 'spotify0101.firebaseapp.com',
  //   storageBucket: 'spotify0101.appspot.com',
  // );
}
